<<<<<<< HEAD
services:
  - type: web
    name: smart-office-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: AIzaSyBNKMf03YvW5uvXcbUxfZsVEnQ0R8belJs
        sync: false
      - key: GEN_MODEL
        value: "gemini-2.0-flash"


=======
services:
  - type: web
    name: smart-office-backend
    env: node
    buildCommand: npm install
    startCommand: npm
>>>>>>> 1740209 (Add Render configuration)
